import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
// import { cn } from "@/lib/utils";

const AppFont = DM_Sans({ subsets: ["latin"] });

// const geist = Geist({subsets:['latin'],variable:'--font-sans'});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Ai Course Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClerkProvider>
        <html lang="en" className={AppFont.className}>
          <body className="min-h-full flex flex-col">
            <Provider>
              {children}
            </Provider>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
